/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReelsRouteImport } from './routes/reels'
import { Route as ExpertiseRouteImport } from './routes/expertise'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsRoute = ReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertiseRoute = ExpertiseRouteImport.update({
  id: '/expertise',
  path: '/expertise',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/expertise': typeof ExpertiseRoute
  '/reels': typeof ReelsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/expertise': typeof ExpertiseRoute
  '/reels': typeof ReelsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/expertise': typeof ExpertiseRoute
  '/reels': typeof ReelsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/consultation'
    | '/contact'
    | '/expertise'
    | '/reels'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/consultation'
    | '/contact'
    | '/expertise'
    | '/reels'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/consultation'
    | '/contact'
    | '/expertise'
    | '/reels'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConsultationRoute: typeof ConsultationRoute
  ContactRoute: typeof ContactRoute
  ExpertiseRoute: typeof ExpertiseRoute
  ReelsRoute: typeof ReelsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expertise': {
      id: '/expertise'
      path: '/expertise'
      fullPath: '/expertise'
      preLoaderRoute: typeof ExpertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConsultationRoute: ConsultationRoute,
  ContactRoute: ContactRoute,
  ExpertiseRoute: ExpertiseRoute,
  ReelsRoute: ReelsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
